export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
ZSH_THEME=""
export PATH=~/.local/bin:~/.cargo/bin:/bin:/usr/local/bin
eval "$(starship init zsh)"
if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi
bindkey -s '^f' '~/dotfiles/usr/bin/tmuxCreate\n'
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [ -z "$WAYLAND_DISPLAY" ] && [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    echo
    echo "Pilih mode:"
    echo "1) Shell saja"
    echo "2) Session grafis (Wayland/X)"
    echo -n "Pilihan [1/2]: "
    read -r MODE

    case "$MODE" in
        2)

            if command -v niri >/dev/null; then
                export ELECTRON_OZONE_PLATFORM_HINT=wayland
                exec niri --session
            else
                exec startx
            fi
            ;;
        *)
            echo "Masuk shell..."
            ;;
    esac
fi
#for voidlinux
alias xi="sudo xbps-install -Syu"
alias ls="ls --color=auto"
alias xs="sudo xbps-query -Rs"
alias xrm="sudo xbps-remove -R"
